/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:82d6c7b8-07a6-4930-9e2e-7fd0be2c4997",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_zLtwcozPt",
    "aws_user_pools_web_client_id": "cuunadqvsr6o0aol1397une04"
    /*"oauth": {
        "domain": "ocpp-webapp-dev.auth.ap-south-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:4200/home/",
        "redirectSignOut": "http://localhost:4200/login/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS"*/
};


export default awsmobile;
