/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "ap-south-1",
    "aws_cognito_identity_pool_id": "ap-south-1:5f0590e0-cfd5-4304-85eb-b4025f79e80c",
    "aws_cognito_region": "ap-south-1",
    "aws_user_pools_id": "ap-south-1_9LluCyELY",
    "aws_user_pools_web_client_id": "4lbno8fht5mrgc9dvr177aida4"
};

export default awsmobile;
